backend:
  name: git-gateway

media_folder: 'site/static/img' # Folder where user uploaded files should go
public_folder: 'img'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      # - file: 'site/content/_index.md'
      #   label: 'Home Page'
      #   name: 'home'
      - file: 'site/content/food/_index.md'
        label: 'Food'
        name: 'food'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Sezioni,
              name: items,
              widget: list,
              fields:
                [
                  { label: Titolo, name: title, widget: string },
                  { label: Descrizione, name: description, widget: text },
                  {
                    label: Piatti,
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Nome, name: name, widget: string },
                        { label: Descrizione, name: description, widget: text },
                        { label: Prezzo, name: price, widget: string },
                        {
                          label: Piccantezza,
                          name: spicy,
                          widget: number,
                          hint: Inserisci un valore numerico,
                          required: false
                        },
                      ],
                  },
                ],
            }
