backend:
  name: git-gateway

media_folder: 'site/static/img' # Folder where user uploaded files should go
public_folder: 'img'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'site/content/_index.md'
        label: 'Home page'
        name: 'home'
        fields:
          - {
              label: Sezioni,
              name: sections,
              widget: list,
              fields:
                [
                  { label: Titolo, name: title, widget: string },
                  { label: Immagine, name: image, widget: image },
                  {
                    label: Link,
                    name: link,
                    widget: string,
                    hint: 'Meglio se non lo cambi questo fra',
                  },
                ],
            }
      - file: 'site/content/food/_index.md'
        label: 'Food'
        name: 'food'
        fields:
          - {
              label: Sezioni,
              name: items,
              widget: list,
              fields:
                [
                  { label: Titolo, name: title, widget: string },
                  {
                    label: Descrizione,
                    name: description,
                    widget: text,
                    required: false,
                  },
                  {
                    label: Piatti,
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Nome, name: name, widget: string },
                        {
                          label: Descrizione,
                          name: description,
                          widget: text,
                          required: false,
                        },
                        { label: Immagine, name: image, widget: image },
                        { label: Prezzo, name: price, widget: string },
                        {
                          label: Piccantezza,
                          name: spicy,
                          widget: number,
                          hint: Inserisci un valore numerico,
                          required: false,
                        },
                      ],
                  },
                ],
            }
      - file: 'site/content/drinks/_index.md'
        label: 'Drinks'
        name: 'drinks'
        fields:
          - {
              label: Sezioni,
              name: items,
              widget: list,
              fields:
                [
                  { label: Titolo, name: title, widget: string },
                  {
                    label: Descrizione,
                    name: description,
                    widget: text,
                    required: false,
                  },
                  {
                    label: Drinks,
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Nome, name: name, widget: string },
                        {
                          label: Descrizione,
                          name: description,
                          widget: text,
                          required: false,
                        },
                        { label: Immagine, name: image, widget: image },
                        { label: Prezzo, name: price, widget: string },
                      ],
                  },
                ],
            }
      - file: 'site/content/beers/_index.md'
        label: 'Beers'
        name: 'beers'
        fields:
          - {
              label: Sezioni,
              name: items,
              widget: list,
              fields:
                [
                  { label: Titolo, name: title, widget: string },
                  {
                    label: Descrizione,
                    name: description,
                    widget: text,
                    required: false,
                  },
                  {
                    label: Drinks,
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Nome, name: name, widget: string },
                        {
                          label: Descrizione,
                          name: description,
                          widget: text,
                          required: false,
                        },
                        { label: Immagine, name: image, widget: image },
                        { label: Prezzo, name: price, widget: string },
                      ],
                  },
                ],
            }
      - file: 'site/content/wines/_index.md'
        label: 'Wines'
        name: 'wines'
        fields:
          - {
              label: Sezioni,
              name: items,
              widget: list,
              fields:
                [
                  { label: Titolo, name: title, widget: string },
                  {
                    label: Descrizione,
                    name: description,
                    widget: text,
                    required: false,
                  },
                  {
                    label: Drinks,
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Nome, name: name, widget: string },
                        {
                          label: Descrizione,
                          name: description,
                          widget: text,
                          required: false,
                        },
                        { label: Immagine, name: image, widget: image },
                        { label: Prezzo, name: price, widget: string },
                      ],
                  },
                ],
            }
